name: Build and Test
 
on: pull_request

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - run: docker build --rm -f docker/Dockerfile -t docker-java-mecab:latest .
    - uses: docker://poad/docker-openjdk:11-zulu-buster
    - run: ./gradlew jibDockerBuild
  